export interface Book {
  id: string | number
  title: string
  series: string
  year: number
  categories: string[]
}

export const sandersonWorks: Book[] = [
  { id: 1, title: "Elantris", year: 2005, series: "Elantris", categories: ["Novels", "Cosmere"] },
  { id: 2, title: "The Final Empire", year: 2006, series: "Mistborn Era 1", categories: ["Novels", "Cosmere"] },
  {
    id: 3,
    title: "The Hope of Elantris",
    year: 2006,
    series: "Elantris (short story)",
    categories: ["Shorts & Novellas", "Cosmere"],
  },
  {
    id: 4,
    title: "Alcatraz Versus the Evil Librarians",
    year: 2007,
    series: "Alcatraz",
    categories: ["Novels", "Junior & YA", "Non-Cosmere"],
  },
  { id: 5, title: "The Well of Ascension", year: 2007, series: "Mistborn Era 1", categories: ["Novels", "Cosmere"] },
  {
    id: 6,
    title: "Alcatraz Versus the Scrivener's Bones",
    year: 2008,
    series: "Alcatraz",
    categories: ["Novels", "Junior & YA", "Non-Cosmere"],
  },
  {
    id: 7,
    title: "Defending Elysium",
    year: 2008,
    series: "Standalone",
    categories: ["Shorts & Novellas", "Non-Cosmere", "Junior & YA"],
  },
  { id: 8, title: "The Hero of Ages", year: 2008, series: "Mistborn Era 1", categories: ["Novels", "Cosmere"] },
  {
    id: 9,
    title: "Alcatraz Versus the Knights of Crystallia",
    year: 2009,
    series: "Alcatraz",
    categories: ["Novels", "Junior & YA", "Non-Cosmere"],
  },
  { id: 10, title: "The Gathering Storm", year: 2009, series: "The Wheel of Time", categories: ["WOT Novels"] },
  { id: 11, title: "Warbreaker", year: 2009, series: "Warbreaker", categories: ["Novels", "Cosmere"] },
  {
    id: 12,
    title: "Alcatraz Versus the Shattered Lens",
    year: 2010,
    series: "Alcatraz",
    categories: ["Novels", "Junior & YA", "Non-Cosmere"],
  },
  {
    id: 13,
    title: "The Way of Kings",
    year: 2010,
    series: "The Stormlight Archive",
    categories: ["Novels", "Cosmere"],
  },
  { id: 14, title: "Towers of Midnight", year: 2010, series: "The Wheel of Time", categories: ["WOT Novels"] },
  {
    id: 15,
    title: "I Hate Dragons",
    year: 2011,
    series: "Standalone (short story)",
    categories: ["Shorts & Novellas", "Non-Cosmere"],
  },
  {
    id: 16,
    title: "Infinity Blade: Awakening",
    year: 2011,
    series: "Infinity Blade (novella)",
    categories: ["Shorts & Novellas", "Non-Cosmere"],
  },
  { id: 17, title: "The Alloy of Law", year: 2011, series: "Mistborn Era 2", categories: ["Novels", "Cosmere"] },
  {
    id: 18,
    title: "The Eleventh Metal",
    year: 2011,
    series: "Mistborn Era 1 (short story)",
    categories: ["Shorts & Novellas", "Cosmere"],
  },
  {
    id: 19,
    title: "Heuristic Algorithm and Reasoning Response Engine",
    year: 2012,
    series: "Standalone (with Skar)",
    categories: ["Shorts & Novellas", "Non-Cosmere"],
  },
  { id: 20, title: "Legion", year: 2012, series: "Legion (novella)", categories: ["Shorts & Novellas", "Non-Cosmere"] },
  {
    id: 21,
    title: "The Emperor's Soul",
    year: 2012,
    series: "Elantris (novella)",
    categories: ["Shorts & Novellas", "Cosmere"],
  },
  { id: 22, title: "A Memory of Light", year: 2013, series: "The Wheel of Time", categories: ["WOT Novels"] },
  {
    id: 23,
    title: "Allomancer Jak and the Pits of Eltania",
    year: 2013,
    series: "Mistborn Era 2 (short story)",
    categories: ["Shorts & Novellas", "Cosmere"],
  },
  {
    id: 24,
    title: "Mitosis",
    year: 2013,
    series: "The Reckoners (short story)",
    categories: ["Shorts & Novellas", "Non-Cosmere", "Junior & YA"],
  },
  {
    id: 25,
    title: "River of Souls",
    year: 2013,
    series: "The Wheel of Time (short story)",
    categories: ["WOT Shorts & Novellas"],
  },
  {
    id: 26,
    title: "Shadows for Silence in the Forests of Hell",
    year: 2013,
    series: "Threnody (novella)",
    categories: ["Shorts & Novellas", "Cosmere"],
  },
  {
    id: 27,
    title: "Steelheart",
    year: 2013,
    series: "The Reckoners",
    categories: ["Novels", "Non-Cosmere", "Junior & YA"],
  },
  {
    id: 28,
    title: "Legion: Skin Deep",
    year: 2014,
    series: "Legion (novella)",
    categories: ["Shorts & Novellas", "Non-Cosmere"],
  },
  {
    id: 29,
    title: "Sixth of the Dusk",
    year: 2014,
    series: "First of the Sun (novella)",
    categories: ["Shorts & Novellas", "Cosmere"],
  },
  { id: 30, title: "Starsight", year: 2014, series: "Skyward", categories: ["Novels", "Non-Cosmere", "Junior & YA"] },
  {
    id: 31,
    title: "Words of Radiance",
    year: 2014,
    series: "The Stormlight Archive",
    categories: ["Novels", "Cosmere"],
  },
  {
    id: 32,
    title: "Firefight",
    year: 2015,
    series: "The Reckoners",
    categories: ["Novels", "Non-Cosmere", "Junior & YA"],
  },
  {
    id: 33,
    title: "Perfect State",
    year: 2015,
    series: "Standalone (novella)",
    categories: ["Shorts & Novellas", "Non-Cosmere"],
  },
  { id: 34, title: "Shadows of Self", year: 2015, series: "Mistborn Era 2", categories: ["Novels", "Cosmere"] },
  {
    id: 35,
    title: "Alcatraz Versus the Dark Talent",
    year: 2016,
    series: "Alcatraz",
    categories: ["Novels", "Junior & YA", "Non-Cosmere"],
  },
  {
    id: 36,
    title: "Calamity",
    year: 2016,
    series: "The Reckoners",
    categories: ["Novels", "Non-Cosmere", "Junior & YA"],
  },
  {
    id: 37,
    title: "Edgedancer",
    year: 2016,
    series: "The Stormlight Archive (novella)",
    categories: ["Shorts & Novellas", "Cosmere"],
  },
  {
    id: 38,
    title: "Infinity Blade: Redemption",
    year: 2016,
    series: "Infinity Blade (novella)",
    categories: ["Shorts & Novellas", "Non-Cosmere"],
  },
  { id: 39, title: "The Bands of Mourning", year: 2016, series: "Mistborn Era 2", categories: ["Novels", "Cosmere"] },
  {
    id: 40,
    title: "White Sand I",
    year: 2016,
    series: "White Sand (graphic novel)",
    categories: ["Cosmere", "Non-Cosmere"],
  },
  {
    id: 41,
    title: "White Sand: Prose / related",
    year: 2016,
    series: "White Sand (prose)",
    categories: ["Collections"],
  },
  {
    id: 42,
    title: "Snapshot",
    year: 2017,
    series: "Standalone (novella)",
    categories: ["Shorts & Novellas", "Non-Cosmere"],
  },
  { id: 43, title: "Oathbringer", year: 2017, series: "The Stormlight Archive", categories: ["Novels", "Cosmere"] },
  {
    id: 44,
    title: "Lies of the Beholder",
    year: 2018,
    series: "Legion (novella)",
    categories: ["Shorts & Novellas", "Non-Cosmere"],
  },
  { id: 45, title: "Skyward", year: 2018, series: "Skyward", categories: ["Novels", "Non-Cosmere", "Junior & YA"] },
  {
    id: 46,
    title: "White Sand II",
    year: 2018,
    series: "White Sand (graphic novel)",
    categories: ["Cosmere", "Non-Cosmere"],
  },
  {
    id: 47,
    title: "A Fire Within the Ways",
    year: 2019,
    series: "The Wheel of Time (short story)",
    categories: ["WOT Shorts & Novellas"],
  },
  { id: 48, title: "Starsight", year: 2019, series: "Skyward", categories: ["Novels", "Non-Cosmere", "Junior & YA"] },
  {
    id: 49,
    title: "White Sand III",
    year: 2019,
    series: "White Sand (graphic novel)",
    categories: ["Cosmere", "Non-Cosmere"],
  },
  {
    id: 50,
    title: "Dawnshard",
    year: 2020,
    series: "The Stormlight Archive (novella)",
    categories: ["Shorts & Novellas", "Cosmere"],
  },
  { id: 51, title: "Rhythm of War", year: 2020, series: "The Stormlight Archive", categories: ["Novels", "Cosmere"] },
  {
    id: 52,
    title: "The Original",
    year: 2020,
    series: "Standalone (with Mary Robinette Kowal)",
    categories: ["Shorts & Novellas", "Audiobook", "Non-Cosmere"],
  },
  {
    id: 53,
    title: "The Way of Kings Prime",
    year: 2020,
    series: "Sanderson Curiosities",
    categories: ["Go Full Sando", "Non-Cosmere"],
  },
  {
    id: 54,
    title: "Dark One",
    year: 2021,
    series: "Dark One (graphic novel)",
    categories: ["Graphic Novels", "Other", "Non-Cosmere"],
  },
  {
    id: 55,
    title: "Evershore",
    year: 2021,
    series: "Skyward (novella)",
    categories: ["Shorts & Novellas", "Non-Cosmere", "Junior & YA"],
  },
  {
    id: 56,
    title: "ReDawn",
    year: 2021,
    series: "Skyward (novella)",
    categories: ["Shorts & Novellas", "Non-Cosmere", "Junior & YA"],
  },
  { id: 57, title: "Cytonic", year: 2021, series: "Skyward", categories: ["Novels", "Non-Cosmere", "Junior & YA"] },
  {
    id: 58,
    title: "Stephen Leeds: Death and Faxes",
    year: 2022,
    series: "Legion (audiobook)",
    categories: ["Shorts & Novellas", "Non-Cosmere"],
  },
  { id: 59, title: "The Lost Metal", year: 2022, series: "Mistborn Era 2", categories: ["Novels", "Cosmere"] },
  {
    id: 60,
    title: "Bastille Versus the Evil Librarians",
    year: 2022,
    series: "Alcatraz (co-written)",
    categories: ["Novels", "Junior & YA", "Non-Cosmere"],
  },
  {
    id: 61,
    title: "Tress of the Emerald Sea",
    year: 2023,
    series: "Hoid's Travails",
    categories: ["Novels", "Cosmere"],
  },
  {
    id: 62,
    title: "Yumi and the Nightmare Painter",
    year: 2023,
    series: "Hoid's Travails",
    categories: ["Novels", "Cosmere"],
  },
  { id: 63, title: "The Sunlit Man", year: 2023, series: "Secret Projects", categories: ["Novels", "Cosmere"] },
  {
    id: 64,
    title: "Hyperthief",
    year: 2023,
    series: "Skyward (short story)",
    categories: ["Shorts & Novellas", "Non-Cosmere", "Junior & YA"],
  },
  {
    id: 65,
    title: "Dark One: Forgotten",
    year: 2023,
    series: "Dark One (with Dan Wells)",
    categories: ["Audiobook", "Other", "Non-Cosmere"],
  },
  {
    id: 66,
    title: "The Most Boring Book Ever",
    year: 2024,
    series: "Children's",
    categories: ["Go Full Sando", "Non-Cosmere"],
  },
  {
    id: 67,
    title: "Dragonsteel Prime",
    year: 2024,
    series: "Sanderson Curiosities",
    categories: ["Go Full Sando", "Non-Cosmere"],
  },
  { id: 68, title: "Wind and Truth", year: 2024, series: "The Stormlight Archive", categories: ["Novels", "Cosmere"] },
  { id: 69, title: "Isles of the Emberdark", year: 2025, series: "Secret Projects", categories: ["Novels", "Cosmere"] },
  {
    id: 70,
    title: "Tailored Realities",
    year: 2025,
    series: "Short Story Collection",
    categories: ["Shorts & Novellas", "Non-Cosmere"],
  },
  {
    id: 71,
    title: "The Fires of December",
    year: 2026,
    series: "Hoid's Travails",
    categories: ["Novels", "Cosmere"],
  },
]

export const books = sandersonWorks

export function getBooksByCategory(category: string): Book[] {
  if (category === "GO FULL SANDO") {
    return sandersonWorks
  }
  return sandersonWorks.filter((book) => book.categories.includes(category))
}
